server:
  port: 8080
  servlet:
    session:
      timeout: 5m # 设置session的有效期为五分钟

spring:
#  Spring Boot 2.4为了提升对Kubernetes的支持 将 spring.profiles 作废了
#  profiles:
#    active: dal,web,config,image
# 替换上面作废的spring.profiels.actice配置参数
  config:
    import: application-dal.yml,application-web.yml,application-config.yml,application-image.yml,application-email.yml

  main:
    allow-circular-references: true
  mvc:
    async:
      request-timeout:
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: true # 当实际使用的数据库不支持liquibase，如 mariadb 时，将这个参数设置为false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

servlet:
  tomcat:
    max-swallow-size: -1 # 解决上传图片超过2MB之后，出现连接重置的问题

security:
  salt: tech_π # 密码加盐, 更安全的做法是每个用户的密码使用独立的盐，并将其保存在用户表中
  salt-index: 3 # 盐插入的位置


# 默认的数据库名
database:
  name: pai_coding

# mybatis 相关统一配置
mybatis-plus:
  configuration:
    #开启下划线转驼峰
    map-underscore-to-camel-case: true
