spring:
  datasource:
    url: jdbc:mysql://prod.hhui.top/${database.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: prod_root
    password:
  redis:
    host: localhost
    port: 6379
    password: