view:
  site:
    websiteName: 技术派
    websiteLogoUrl: https://paicoding.com/img/logo.svg
    websiteFaviconIconUrl: https://paicoding.com/img/icon.png
    contactMeTitle: 联系我 - louzai
    contactMeWxQrCode: https://blog.hhui.top/hexblog/imgs/info/wx.jpg
    pageSize: 20
    cdnImgStyle:
    websiteRecord: 豫ICP备2021038026号-3
    wxLoginUrl: http://weixin.qq.com/r/FS9waAPEg178rUcL93oH
    host: https://paicoding.com
    welcomeInfo: 欢迎来到技术派，戳<a href="/article/detail/1">技术派全方位视角解读</a>了解我们