view:
  site:
    websiteName: 技术派
    websiteLogoUrl: /img/logo.svg
    websiteFaviconIconUrl: https://blog.hhui.top/hexblog/images/avatar.jpg
    contactMeTitle: 联系我 - liuyueyi25
    contactMeWxQrCode: https://blog.hhui.top/hexblog/imgs/info/wx.jpg
    pageSize: 20
    cdnImgStyle:
    websiteRecord: 豫ICP备2021038026号-3
    wxLoginUrl: http://weixin.qq.com/r/FS9waAPEg178rUcL93oH
    host: https://forum.hhui.top
