server:
  port: 8080

spring:
  profiles:
    active: dal,web,config
  main:
    allow-circular-references: true
  mvc:
    async:
      request-timeout:

# mybatis 相关统一配置
mybatis-plus:
  configuration:
    #开启下划线转驼峰
    map-underscore-to-camel-case: true
