view:
  site:
    websiteName: 技术派
    websiteLogoUrl: https://blog.hhui.top/hexblog/images/avatar.jpg
    websiteFaviconIconUrl: https://blog.hhui.top/hexblog/images/avatar.jpg
    contactMeTitle: 联系我 - liuyueyi25
    contactMeWxQrCode: https://blog.hhui.top/hexblog/imgs/info/wx.jpg
    pageSize: 20
    cdnImgStyle:
    websiteRecord: 备案记录
    wxLoginUrl: http://weixin.qq.com/r/FS9waAPEg178rUcL93oH
    host: http://127.0.0.1:8080