net:
  proxy:
    # 代理相关信息
    - ip: 127.0.0.1
      port: 1080
      type: SOCKS
    - ip: 127.0.0.1
      port: 1700
      type: SOCKS



# chatgpt
chatgpt:
  main: GPT_3_5_TURBO
  conf:
    GPT_3_5_TURBO:
      keys:
        - xx1
        - xx2
      proxy: true # 表示走上面的代理进行访问
      apiHost: https://api.openai.com/
      timeOut: 900
      maxToken: 3000
    GPT_4:
      keys:
        -
      proxy: true
      apiHost: https://api.openai.com/
      timeOut: 900
      maxToken: 200000


# 讯飞AI
xunfei:
  hostUrl: http://spark-api.xf-yun.com/v1.1/chat
  appId:
  apiKey:
  apiSecret: