spring:
  datasource: #单数据源
    url: jdbc:mysql://localhost:3306/${database.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:
  dynamic: # 动态数据源
#    primary: master # 这个表示默认的数据源
    datasource:
      master:
        # 数据库名，从配置 database.name 中获取
        url: jdbc:mysql://localhost:3306/${database.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password:
      slave:
        # 数据库名，从配置 database.name 中获取
        url: jdbc:mysql://localhost:3306/${database.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: readonly
        password:
  redis:
    host: localhost
    port: 6379
    password:

#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志